name: Get Releases

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # every midnight GMT

jobs:
  releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Cache Python Packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
        env:
          PIP_CACHE_DIR: ~/.cache/pip

      - name: Run Script
        env:
          HEADERS: ${{ secrets.HEADERS }}
          HASH: ${{ secrets.HASH }}
          AJAX: ${{ secrets.AJAX }}
        run: python main.py

      - name: Commit the changes
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" &&
            export COMMIT_HASH=$(git rev-parse HEAD) &&
            exit 0
          git push